### PR TITLE
Created a simple script that generates viewsync links

### PR DESCRIPTION
**Pull request by klokkenman1**
Not sure if this is a feature that is at all wanted, but creating viewsync's can be an hassle and links to video's are already documented on this site so generating a viewsync url can be easily done.

### CODE REVIEW

**Comment by bcranton** [comment]
This is really cool, and actually something a few people have suggested. I will have to do some editing to add a 4th column to the tables for the viewsync links, but once I do that it should be no problem to merge it

**Comment by klokkenman1** [comment]
For now i just replaced the number in the first collumn with the number in a <a> tag but you wouldnt know it was there if it wasnt told.

**Comment by bcranton** [comment]
Oh awesome, I hadn't even realized. I will go ahead and merge, and work on making it a bit more visually obvious too :)

**Comment by bcranton** [comment]
Hey, just to let you know, I found a bug after merging it.

In situations where a contestant didn't upload a video (ie, MALF in NES and SEGA) that day's viewsync and all subsequent ones would break. I fixed it up though 👍

**Pull request merged**
