### PR TITLE
Automatically create/place medal images

### PR DESCRIPTION
**Pull request by shocknoble**
Added logic to automatically add the medal icons based on the player's score in the Competitor.js file

Now all you'll need to do is edit the json body with their medal totals and it will add each of the medals to the page! This is what you were after, correct?

### CODE REVIEW

**Comment by bcranton** [comment]
Yea, this is exactly what I was after. Thanks a lot, it is really appreciated.

**Comment by shocknoble** [comment]
Killer!! Absolutely thrilled to be able to help my man. I will work on this some more maybe this weekend. At some point I bet we can have the whole thing running itself 💯 Let me know if you think of anything and wanna bounce ideas back and forth or whatever!

**Comment by bcranton** [comment]
At this point, the only thing I that immediately comes to mind that could really be improved on, is if we had a database of some kind that the we could pull from. But there are a couple issues with that.

1. I again have no idea how those really work lol. Before this, 99% of my recent programming was in Python writing some automation scripts for work, so I have really been using this to learn about HTML/CSS/JS, and Git

2. I am running the website on Netlify, and it doesn't support any server-side operations. So, if we did implement something like that, I imagine it would have to be utilizing something similar to the JSON you created that the medals page pulls from.

**Comment by shocknoble** [comment]
Yeah... databases are my least favorite thing in the programming world. From what I understand (huge disclaimer there), I don't think we can do any sort of persistent storage without server-side services. I have some pretty decent experience with nodejs and running them on digital ocean. But at this time on a Friday afternoon I cannot even wrap my head around where to start with something like that, hahahaha.

**Comment by bcranton** [comment]
Yea, I am not sweating it. At this point, updating the website only takes less than a minute. The larger time barrier is spending like 20 minutes trying to figure out who won each game exactly lol

**Comment by shocknoble** [comment]
We will work on that part sometime soon too and that's what I'm really looking forward to!

**Comment by bcranton** [comment]
Lol, what do you possibly have in mind in regards to that?

**Comment by shocknoble** [comment]
I think if we could come up with a consistent format (and if they were down to participate), we could have the crew put their score in the video description following that format and we'd gather it automatically based off of that!

**Comment by bcranton** [comment]
Yea, if there was some consistent way for them to place a score in the description that would certainly be quite easy. However, I really doubt we could convince all of them to go through the effort of that

**Pull request merged**
