### PR TITLE
Added competitor class, replaced medal page standings logic

### PR DESCRIPTION
**Pull request by shocknoble**
The competitor class creates an object oriented class for each of the three competitors. There is a body of json within Competitor.js that, when updated, will reduce the amount of places where score/standing need to be updated. I've shown an example of this at the bottom of medalCount.js, by replacing the logic required to determine who is in what place.

### CODE REVIEW

**Comment by bcranton** [comment]
Oh man, this is real programmer hours now lol

Nice job turning this into an actual object. Looks good, and much better written than what I had before.

Question though, it looks like I have to manually update the placing for each object (competitor) and manually add the medal each day (the ones in the "medals" class). Am I reading this code properly?

I ask, because right now I just add the medal and the rest is calculated with my janky JS lol
Is it possible for the Gold/Silver/Bronze attribute of each object to be calculated based off the medal count? As you can likely tell, I basically have 0 idea of what I am doing with JS, so even if you can just guide me in the right direction I can likely add that bit myself

**Comment by bcranton** [comment]
Or alternatively, I guess it would likely make more sense for the medals to be added based off the number I give to the object. Hmmmm, I can likely figure that out

**Comment by shocknoble** [comment]
I am working on that right now, actually! The goal is for you to be able to just go into the Competitor.js file and update the number of each medal for the three of them, and then the medal icons will be added to that page based off of that number. Am I making sense?

**Comment by bcranton** [comment]
> I am working on that right now, actually! The goal is for you to be able to just go into the Competitor.js file and update the number of each medal for the three of them, and then the medal icons will be added to that page based off of that number. Am I making sense?

Yea that is exactly what I had in mind, it would be perfect!

**Pull request merged**
