### PR TITLE
Add /#nospoiler feature

### PR DESCRIPTION
**Pull request by amalloy**
Appending #nospoiler to a URL will hide the results, showing only video links

### CODE REVIEW

**Comment by amalloy** [comment]
See it in action at https://deploy-preview-20--awesome-babbage-ce1e9f.netlify.app/#nospoiler

**Comment by bcranton** [comment]
Seems good :)

Small issue though, the "comment" class is only there if the game doesn't have an incremental/traditional scoring system.

So, if "comment" is absent, then scoreCount.js will add the score to the "totals" table.

If you check out Escape from Tarkov, you will see what I mean, as it has a mix of both.

**Comment by amalloy** [comment]
Resolved. Both Tarkov and CoD work now.

**Comment by bcranton** [comment]
Cool merging now!

I will expand on this in the next few days to add a header at the top of the website advising users of it, and also expanding it to cover up the medals sections too.

**Comment by bcranton** [comment]
Spoke too soon, looks like the medals are already hidden.

**Pull request merged**
