### PR TITLE
Updating content list to source from single file

### PR DESCRIPTION
**Pull request by SQLJames**
Updating content list to source from single file. I wasn't able to get the JS to play nice and add the active class to the dropdown item. I removed that section of code from my final pull request. But everything else seems to be working fine.

### CODE REVIEW

**Comment by bcranton** [comment]
At work right now, so I haven't looked into it very deeply, but I'd imagine you could pass an argument to the JS function that could specify which link is active.

I may play with that sometime this week, if you don't get to it first.

Otherwise it looks great 👍

**Comment by krainboltgreene** [comment]
I was literally coming to work on this very thing. I think that this is a good move now that this is so huge. [It also lets us do some more interesting displays of the data](https://twitter.com/krainboltgreene/status/1282517608059686914).

That said it's powerful to have this be statically generated as well. Do we have to introduce frontend javascript?

**Comment by bcranton** [comment]
Yea, that is something that I've mentioned to various people as something that I wish I had done from the start. But, at the time I didn't even known they were a thing.

Migrating it over to a SSG is something I do still want to do, just haven't got around to really learning any of them. Do you have a recommendation between Gatsby, Hugo, Jekyll, etc?

**Comment by krainboltgreene** [comment]
Gatsby looks cool, but frankly any would do. I've used them all and they're all pretty nice. We can setup a github action for it.

**Comment by bcranton** [comment]
Yea, from what I have found Gatsby seems to be the new best option. The website is actually hosted through Netlify not Github Pages, but I know they support Gatsby as well so that should be fine.

What I will likely do is start working on migrating this over, and then ultimately archive this repo, and create a new repo for the Gatsby version of the website.

**Comment by krainboltgreene** [comment]
A good first start would be creating a small data file (csv?) full of all the wins. All content can be generated from that file.

**Comment by bcranton** [comment]
Yeah i played with it briefly today, and it looks like it should be easy enough to programmatically create pages from json (or even yaml).

So that's my running plan.

**Comment by SQLJames** [comment]
If you guys want some help on the new repo let me know, happy to contribute some time. :)

**Comment by bcranton** [comment]
Hey, just letting you guys (@SQLJames  @krainboltgreene) know we have a working Gatsby branch setup that still has a lot of work that needs doing 👍

Also, I created a "project" tab for the repo, that has things that need to be completed or started if you feel so inclined.

Since we are migrating to Gatsby, I am going to close this pull request since the navigation template is implemented in the Gatsby branch. Thanks 😄

**Pull request closed without merging**
